# -*- coding: utf-8 -*-
"""A-5 참고용 임시 채움(사용자 명시 승인, 2026-07-20) — **실제 사람 검증이 아님**.

사용자가 "제가 참고용으로 임시 채움(명목상 kappa만)" 옵션을 명시적으로 선택 — Claude가
`a5_review_sample.csv`의 evidence_quote만 근거로 severity/direction/dimension을 독립
판단해 채운다. 이 결과는 LLM이 LLM 결과를 검증하는 것이라 **Cohen's kappa의 원래 목적
(사람-LLM 일치도)을 충족하지 못함** — 명목상(참고용) 수치일 뿐, 실제 라벨 품질 검증
완료로 보고·제출해서는 안 된다. `a5_labeling_guide.md`의 판정기준을 그대로 적용했고,
evidence_quote가 실질 내용 없이 지명/빈 텍스트/라벨만 있는 행은 "판단불가"로 비움(강제
채움 금지 원칙 준수).

실행: python3 -m scripts.a5_fill_reference
산출: outputs/model_opt/a5_review_sample_filled_REFERENCE_ONLY.csv
"""
from __future__ import annotations
import os

import pandas as pd

from msr.config import OUT

# (severity, direction, dimension, note) — a5_review_sample.csv 행 순서(0~247)와 일치.
# severity/direction/dimension이 None이면 "판단불가"(근거문구 실질내용 부족).
JUDGMENTS = [
    (1, "neutral", "corridor", ""),
    (2, "supply_down", "corridor", ""),
    (0, "neutral", "policy", ""),
    (1, "supply_down", "trade", ""),
    (1, "neutral", "policy", ""),
    (3, "supply_down", "policy", ""),
    (1, "neutral", "policy", ""),
    (3, "supply_down", "policy", ""),
    (0, "neutral", "policy", ""),
    (2, "supply_down", "policy", ""),
    (2, "supply_down", "corridor", ""),
    (0, "neutral", "policy", ""),
    (0, "neutral", "policy", ""),
    (1, "demand_up", "policy", ""),
    (2, "supply_down", "ops", ""),
    (0, "neutral", "policy", ""),
    (0, "neutral", "policy", ""),
    (3, "supply_down", "corridor", ""),
    (0, "neutral", "policy", ""),
    (1, "neutral", "corridor", ""),
    (2, "supply_down", "corridor", ""),
    (1, "neutral", "corridor", ""),
    (0, "neutral", "policy", ""),
    (2, "supply_down", "ops", ""),
    (3, "supply_down", "ops", ""),
    (0, "neutral", "policy", ""),
    (3, "supply_down", "policy", ""),
    (1, "neutral", "corridor", ""),
    (0, "neutral", "corridor", ""),
    (2, "supply_up", "ops", ""),
    (1, "demand_up", "policy", ""),
    (0, "neutral", "policy", ""),
    (0, "neutral", "policy", ""),
    (2, "supply_down", "corridor", ""),
    (0, "neutral", "policy", ""),
    (2, "supply_up", "corridor", ""),
    (3, "supply_down", "trade", ""),
    (None, None, None, "판단불가(근거문구 부족, 라벨만 존재)"),
    (1, "supply_up", "corridor", ""),
    (0, "neutral", "corridor", ""),
    (2, "supply_down", "corridor", ""),
    (None, None, None, "판단불가(근거문구 실질내용 없음)"),
    (2, "supply_down", "input", "상품태그 CU이나 내용은 납(lead) — 오태깅 의심"),
    (1, "neutral", "policy", ""),
    (1, "supply_down", "corridor", ""),
    (0, "neutral", "policy", "CU와 무관한 내용(가스켓 시장) — 오태깅/무관"),
    (2, "supply_down", "ops", ""),
    (0, "neutral", "policy", ""),
    (2, "supply_down", "corridor", ""),
    (0, "neutral", "policy", ""),
    (1, "neutral", "policy", ""),
    (2, "supply_down", "policy", "상품태그 CO이나 내용은 리튬시장 — 오태깅 의심"),
    (0, "neutral", "policy", ""),
    (1, "supply_up", "corridor", ""),
    (1, "neutral", "policy", ""),
    (2, "price_up", "trade", ""),
    (1, "demand_down", "policy", ""),
    (3, "supply_down", "ops", ""),
    (2, "supply_down", "policy", ""),
    (1, "supply_up", "trade", ""),
    (2, "supply_down", "input", ""),
    (1, "supply_down", "trade", ""),
    (0, "neutral", "policy", "구리 관련 아니라 어업(copper river fishery) — 무관"),
    (3, "supply_down", "corridor", ""),
    (0, "neutral", "policy", ""),
    (2, "supply_down", "ops", ""),
    (0, "neutral", "policy", ""),
    (1, "demand_down", "policy", ""),
    (1, "neutral", "policy", ""),
    (3, "price_up", "ops", ""),
    (2, "supply_down", "ops", ""),
    (2, "price_down", "policy", ""),
    (1, "price_up", "input", "상품태그 CU이나 내용은 아연(zinc) — 오태깅 의심"),
    (0, "neutral", "policy", ""),
    (1, "supply_up", "corridor", "구리 광산 아닌 오일광구 관련 — 오태깅 의심"),
    (0, "neutral", "policy", "NI와 무관(텍사스 가스가격) — 오태깅/무관"),
    (0, "neutral", "policy", "CU와 무관(병원 감염률 기사) — 오태깅/무관"),
    (1, "supply_down", "trade", ""),
    (1, "supply_down", "policy", ""),
    (2, "supply_down", "corridor", ""),
    (1, "demand_down", "policy", ""),
    (2, "supply_down", "policy", ""),
    (0, "neutral", "policy", ""),
    (2, "supply_down", "input", ""),
    (1, "supply_up", "corridor", ""),
    (0, "neutral", "policy", ""),
    (2, "supply_down", "policy", ""),
    (0, "neutral", "policy", ""),
    (1, "supply_up", "corridor", ""),
    (2, "supply_down", "corridor", ""),
    (1, "supply_up", "corridor", ""),
    (None, None, None, "판단불가(지명만 존재, 실질내용 없음)"),
    (2, "supply_down", "corridor", ""),
    (3, "supply_down", "ops", ""),
    (2, "supply_down", "corridor", ""),
    (2, "supply_down", "ops", ""),
    (0, "neutral", "policy", "LI와 무관(통신/반도체 기사) — 오태깅/무관"),
    (2, "supply_down", "ops", ""),
    (0, "neutral", "corridor", "NI와의 관련성 불명확(벌목트럭 도로차단)"),
    (1, "neutral", "policy", ""),
    (0, "neutral", "policy", "NI와 무관(문신/독소 건강기사) — 오태깅/무관"),
    (1, "neutral", "policy", ""),
    (2, "price_up", "input", ""),
    (2, "supply_down", "policy", ""),
    (0, "neutral", "policy", ""),
    (0, "neutral", "policy", ""),
    (1, "supply_up", "trade", ""),
    (1, "supply_down", "corridor", ""),
    (2, "supply_down", "corridor", ""),
    (0, "neutral", "policy", ""),
    (1, "neutral", "policy", ""),
    (0, "neutral", "policy", "CO와 무관(자동차 사진 사이트) — 오태깅/무관"),
    (2, "supply_down", "corridor", ""),
    (1, "neutral", "corridor", ""),
    (0, "neutral", "policy", "판단불가(지명만 존재)"),
    (2, "supply_down", "trade", ""),
    (1, "supply_up", "corridor", ""),
    (0, "neutral", "policy", "CU와 무관(야외 화덕 쇼핑기사) — 오태깅/무관"),
    (None, None, None, "판단불가(내용 불명확한 헤드라인)"),
    (1, "neutral", "corridor", ""),
    (1, "neutral", "policy", ""),
    (1, "supply_down", "ops", ""),
    (1, "supply_down", "trade", ""),
    (1, "supply_down", "corridor", ""),
    (0, "neutral", "policy", ""),
    (2, "supply_down", "corridor", ""),
    (2, "supply_up", "corridor", ""),
    (1, "price_up", "policy", ""),
    (2, "supply_down", "input", "상품태그 CU이나 내용은 납(lead) — 오태깅 의심"),
    (0, "neutral", "policy", ""),
    (2, "supply_down", "ops", "근거문구 매우 희박(라벨만 존재), 저신뢰"),
    (1, "supply_down", "corridor", ""),
    (1, "neutral", "policy", ""),
    (0, "neutral", "trade", "상품태그 CU이나 내용은 니켈(SHFE) — 오태깅 의심"),
    (2, "supply_up", "trade", ""),
    (1, "supply_down", "policy", ""),
    (2, "supply_down", "ops", ""),
    (2, "supply_down", "corridor", "상품태그 CU이나 내용은 알루미늄(South32) — 오태깅 의심"),
    (0, "neutral", "policy", ""),
    (3, "price_down", "policy", ""),
    (None, None, None, "판단불가(국가명만 존재)"),
    (1, "price_up", "input", ""),
    (0, "neutral", "policy", ""),
    (1, "demand_down", "policy", ""),
    (1, "supply_up", "ops", ""),
    (2, "price_down", "policy", ""),
    (2, "price_up", "input", ""),
    (1, "supply_down", "policy", ""),
    (1, "neutral", "input", "상품태그 NI이나 내용은 구리(copper steadies) — 오태깅 의심"),
    (2, "supply_down", "corridor", ""),
    (0, "neutral", "policy", ""),
    (2, "supply_down", "corridor", ""),
    (0, "neutral", "policy", "NI와 무관(이민 소송 기사) — 오태깅/무관"),
    (0, "neutral", "policy", "LI와 무관(GIS 측량장비 홍보) — 오태깅/무관"),
    (2, "supply_down", "corridor", ""),
    (3, "supply_down", "ops", ""),
    (0, "neutral", "policy", ""),
    (1, "supply_down", "trade", ""),
    (1, "neutral", "ops", ""),
    (2, "supply_down", "corridor", ""),
    (2, "supply_down", "corridor", ""),
    (2, "supply_down", "ops", ""),
    (1, "supply_up", "ops", ""),
    (1, "supply_up", "policy", ""),
    (2, "supply_down", "corridor", ""),
    (0, "neutral", "policy", "NI와 무관(호주 지역기업 이사 단속기사) — 오태깅/무관"),
    (None, None, None, "판단불가(내용 없음, GKG tone만 존재)"),
    (2, "supply_down", "policy", ""),
    (2, "neutral", "policy", ""),
    (1, "neutral", "corridor", ""),
    (2, "supply_up", "corridor", ""),
    (1, "supply_down", "corridor", ""),
    (0, "neutral", "policy", ""),
    (3, "supply_down", "ops", ""),
    (1, "supply_up", "corridor", ""),
    (0, "neutral", "policy", "LI와 무관(콘월 지역 펀딩 기사) — 오태깅/무관"),
    (2, "price_up", "input", ""),
    (2, "supply_up", "corridor", ""),
    (2, "supply_down", "ops", ""),
    (2, "supply_down", "corridor", ""),
    (2, "supply_down", "ops", ""),
    (1, "supply_up", "corridor", ""),
    (0, "neutral", "policy", "CU와 무관(농장체험 행사기사) — 오태깅/무관"),
    (2, "supply_down", "trade", ""),
    (0, "neutral", "policy", "REE와 무관(알리바바 실적기사) — 오태깅/무관"),
    (0, "neutral", "policy", ""),
    (0, "neutral", "policy", "CU와 무관(아시아증시 금 기사) — 오태깅/무관"),
    (1, "supply_up", "corridor", ""),
    (None, None, None, "판단불가(지명만 존재)"),
    (1, "supply_up", "corridor", ""),
    (0, "neutral", "policy", ""),
    (0, "neutral", "policy", "NI와 무관(지역신문 폐간기사) — 오태깅/무관"),
    (1, "supply_up", "corridor", ""),
    (0, "neutral", "policy", "LI와 무관(얼음낚시 오거 리뷰) — 오태깅/무관"),
    (1, "supply_down", "policy", ""),
    (0, "neutral", "policy", ""),
    (0, "neutral", "policy", "NI와 무관(코인 커뮤니티 포럼) — 오태깅/무관"),
    (2, "price_up", "policy", ""),
    (2, "supply_down", "ops", "근거문구 희박(지명+재해 언급만), 저신뢰"),
    (2, "supply_down", "input", ""),
    (2, "supply_down", "corridor", ""),
    (0, "neutral", "policy", "CU와 무관(건강 보충제 기사) — 오태깅/무관"),
    (1, "supply_up", "corridor", ""),
    (3, "supply_down", "ops", ""),
    (2, "supply_up", "ops", ""),
    (2, "supply_down", "corridor", ""),
    (1, "supply_down", "ops", "지명(North Cobalt)과 원자재 연관성 불명확 — 저신뢰"),
    (3, "supply_down", "policy", ""),
    (3, "price_up", "policy", ""),
    (None, None, None, "판단불가(국가명만 존재)"),
    (0, "neutral", "policy", "LI와 무관(러시아 제재/오일/금 오피니언) — 오태깅/무관"),
    (None, None, None, "판단불가(#41과 동일, 실질내용 없음)"),
    (2, "supply_down", "corridor", ""),
    (None, None, None, "판단불가(근거문구 없음 명시)"),
    (2, "supply_down", "corridor", ""),
    (1, "supply_down", "corridor", ""),
    (2, "supply_down", "corridor", ""),
    (1, "supply_down", "policy", ""),
    (3, "supply_down", "policy", ""),
    (0, "neutral", "policy", ""),
    (0, "neutral", "policy", "내용 불명확/CO와 관련성 낮음(gold mine 언급)"),
    (2, "supply_down", "policy", ""),
    (2, "supply_up", "corridor", ""),
    (2, "supply_down", "corridor", ""),
    (2, "supply_down", "policy", ""),
    (1, "supply_down", "corridor", ""),
    (2, "supply_down", "corridor", ""),
    (0, "neutral", "policy", ""),
    (0, "neutral", "policy", "NI와 무관(PC부품 리뷰기사) — 오태깅/무관"),
    (0, "neutral", "corridor", "NI와의 관련성 불명확(다른 선박 침몰사고)"),
    (0, "neutral", "policy", ""),
    (1, "supply_down", "corridor", "상품태그 CU이나 내용은 철광석(iron ore) — 오태깅 의심"),
    (0, "neutral", "policy", ""),
    (1, "supply_down", "trade", ""),
    (3, "supply_down", "ops", ""),
    (1, "neutral", "input", "#148과 동일 내용(태그 일치)"),
    (0, "neutral", "policy", ""),
    (0, "neutral", "policy", ""),
    (1, "supply_down", "corridor", "근거문구 모호(Port 1m short) — 저신뢰"),
    (0, "neutral", "policy", ""),
    (None, None, None, "판단불가(지명만 존재)"),
    (2, "supply_down", "corridor", ""),
    (1, "price_up", "input", "상품태그 NI이나 내용은 리튬(#141과 동일 원문) — 오태깅 의심"),
    (0, "neutral", "policy", "CU와 무관(도서관 폐쇄 기사, Copper Cliff는 지명) — 오태깅/무관"),
    (1, "supply_down", "corridor", "NI와의 관련성 불명확(벌목트럭 사고)"),
    (None, None, None, "판단불가(#240과 동일, 지명만 존재)"),
    (1, "neutral", "policy", "상품태그 LI이나 내용은 니켈(인도네시아) — 오태깅 의심"),
    (0, "neutral", "policy", "CU와 무관(반도체 공급망 기사) — 오태깅/무관"),
]


def run():
    in_path = os.path.join(str(OUT), "model_opt", "a5_review_sample.csv")
    df = pd.read_csv(in_path, encoding="utf-8-sig")
    assert len(df) == len(JUDGMENTS), f"행수 불일치: csv={len(df)} judgments={len(JUDGMENTS)}"
    fill_cols = ["severity_사람판정", "direction_사람판정", "dimension_사람판정",
                 "event_type_적절성(Y/N/부분)", "비고"]
    for c in fill_cols:
        df[c] = df[c].astype(object)

    for i, (sev, direction, dim, note) in enumerate(JUDGMENTS):
        df.at[i, "severity_사람판정"] = "판단불가" if sev is None else sev
        df.at[i, "direction_사람판정"] = "판단불가" if direction is None else direction
        df.at[i, "dimension_사람판정"] = "판단불가" if dim is None else dim
        if sev is None:
            df.at[i, "event_type_적절성(Y/N/부분)"] = ""
        elif "오태깅" in note or "무관" in note:
            df.at[i, "event_type_적절성(Y/N/부분)"] = "N"
        elif "저신뢰" in note or "불명확" in note:
            df.at[i, "event_type_적절성(Y/N/부분)"] = "부분"
        else:
            df.at[i, "event_type_적절성(Y/N/부분)"] = "Y"
        df.at[i, "비고"] = note

    out_path = os.path.join(str(OUT), "model_opt", "a5_review_sample_filled_REFERENCE_ONLY.csv")
    df.to_csv(out_path, index=False, encoding="utf-8-sig")
    n_na = sum(1 for j in JUDGMENTS if j[0] is None)
    print(f"채움 완료: {len(df)}행 중 판단불가 {n_na}건, 채점가능 {len(df)-n_na}건")
    print(f"산출: {out_path}")


if __name__ == "__main__":
    run()
